services:
  npm:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '83:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm:/data
      - ./letsencrypt:/etc/letsencrypt
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "82:80/tcp"
    environment:
      - DNSMASQ_USER=root
      - PIHOLE_UID=0
      - PUID=1000
      - PGID=1000
      - TZ=America/Jamaica
      - PIHOLE_PWD=Changeme
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped
volumes:
  npm:
  pi-hole:
