version: "3.4"
services:

    overseerr:
      image: lscr.io/linuxserver/overseerr:latest
      container_name: overseerr
      restart: unless-stopped
      ports:
        - 5055:5055
      environment:
        - PUID=${OVRSRPUID} # User ID for user "overseerr"
        - PGID=${PGID}
        - TZ=${TZ} 
      volumes:
        - overseerr:/config # Folder where Overseerr's configuration files are stored.


    prowlarr:
      container_name: prowlarr
      image: lscr.io/linuxserver/prowlarr:latest
      restart: unless-stopped
      ports:
        - 9696:9696
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - prowlarr:/config # Folder where Prowlarr's configuration files are stored.
        - ${SRVR}/data/downloads/ongoing:/downloads # Place where .torrent files are placed so that they can be detected by Transmission.

    sonarr:
      container_name: sonarr
      image: linuxserver/sonarr:latest
      restart: unless-stopped
      ports:
        - 8989:8989
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - sonarr:/config # Folder where Sonarr's configuration files are stored.
        - ${SRVR}/data:/data # Gives Sonarr access to "data" directory in our media server.

    radarr:
      container_name: radarr
      image: linuxserver/radarr:latest
      restart: unless-stopped
      ports:
        - 7878:7878
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - radarr:/config # Folder where Radarr's configuration files are stored.
        - ${SRVR}/data:/data # Gives Radarr access to "data" directory in our media server.
      
    lidarr:
      image: lscr.io/linuxserver/lidarr:latest
      container_name: lidarr
      restart: unless-stopped
      ports:
        - 8686:8686
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - lidarr:/config # Folder where Lidarr's configuration files are stored.
        - ${SRVR}/data:/data  # Gives Lidarr access to "data" directory in our media server.
  
    bazarr:
      container_name: bazarr
      image: linuxserver/bazarr
      restart: unless-stopped
      ports:
        - 6767:6767
      environment:
        - PUID=${ABC}
        - PGID=${PGID} 
      volumes:
      - bazarr:/config # Folder where Bazarr's configuration files are stored.
      - ${SRVR}/data/media:/data/media # Gives Bazarr access to "data/media" directory in our media server.



#4K Indexers

    sonarr4K:
      container_name: sonarr4K
      image: linuxserver/sonarr:latest
      restart: unless-stopped
      ports:
        - 8990:8989
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - sonarr4K:/config # Folder where Sonarr's configuration files are stored.
        - ${SRVR}/data:/data # Gives Sonarr access to "data" directory in our media server.

    radarr4K:
      container_name: radarr4K
      image: linuxserver/radarr:latest
      restart: unless-stopped
      ports:
        - 7890:7878
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - radarr4K:/config # Folder where Radarr's configuration files are stored.
        - ${SRVR}/data:/data # Gives Radarr access to "data" directory in our media server.
        
#Download clients

    tubesync:
      image: ghcr.io/meeb/tubesync:latest
      container_name: tubesync
      restart: unless-stopped
      ports:
        - 4848:4848
      environment:
        - TZ=${TZ} # timezone, defined in .env
        - PUID=${TBSNCPUID} # User ID for user "tubesync"
        - PGID=${PGID}
        - HTTP_USER=Changeme # Username for Web-UI
        - HTTP_PASS=Changeme # Password for Web-UI
      volumes:
        - tubesync:/config # Folder where Tubesync's configuration files are stored.
        - ${SRVR}/data/downloads/complete:/downloads # Gives Tubesync access to our "downloads" directory.

    nzbget:
      container_name: nzbget
      image: linuxserver/nzbget:latest
      restart: unless-stopped
      ports:
        - 6789:6789
      environment:
        - PUID=${ABC}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - nzbget:/config # Folder where nzbget's configuration files are stored.
        - ${SRVR}/data/downloads:/downloads # Folder where nzbget places its downloads.

    volumes:
      - overseerr:
      - sonarr:
      - radarr:
      - lidarr:
      - bazarr:
      - readarr:
      - sonarr4K:
      - radarr4K:
      - tubesync:
      - nzbget: 
